/**
 * Generates Respondus plain text format for Blackboard pool import.
 * Correct answer is indicated by an asterisk (*) before the option letter.
 *
 * Format:
 *   1. Question stem
 *   a. Option A
 *   *b. Correct option  ← asterisk marks correct answer
 *   c. Option C
 *   d. Option D
 */
export function generateRespondusFormat(questions, config) {
  const letters = ['a', 'b', 'c', 'd', 'e'];
  let output = '';

  // Header block
  output += `# Summative Assessment — ${config.moduleName}\n`;
  output += `# Academic Level: ${config.academicLevel}\n`;
  output += `# Assessment Weight: ${config.assessmentWeight}% of overall grade\n`;
  output += `# Questions: ${questions.length} | Time: ${config.minutes} minutes\n`;
  output += `# Generated by Summative Assessment Design Assistant\n`;
  output += `# Format: Respondus plain text — import via Newcastle Blackboard Quiz Creator\n`;
  output += `# https://teaching.ncl.ac.uk/bms/bb/\n\n`;

  questions.forEach((q, index) => {
    output += `${index + 1}. ${q.stem}\n`;
    q.options.forEach((option, i) => {
      const letter = letters[i];
      const isCorrect = i === q.correctIndex;
      output += `${isCorrect ? '*' : ''}${letter}. ${option}\n`;
    });
    output += '\n';
  });

  return output;
}

export function downloadRespondusFile(questions, config) {
  const content = generateRespondusFormat(questions, config);
  const safeName = config.moduleName
    .replace(/[^a-z0-9]/gi, '_')
    .replace(/_+/g, '_')
    .toLowerCase();
  const filename = `${safeName}_mcq_assessment.txt`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generates a human-readable review sheet (PDF-printable plain text)
 * with stems, options, correct answers, explanations, and Bloom's levels.
 */
export function generateReviewSheet(questions, config) {
  const letters = ['a', 'b', 'c', 'd', 'e'];
  let output = '';

  output += `QUESTION REVIEW SHEET\n`;
  output += `${'='.repeat(60)}\n`;
  output += `Module: ${config.moduleName}\n`;
  output += `Academic Level: ${config.academicLevel}\n`;
  output += `Assessment Weight: ${config.assessmentWeight}%\n`;
  output += `Questions: ${questions.length} | Time: ${config.minutes} min\n`;
  output += `${'='.repeat(60)}\n\n`;

  questions.forEach((q, index) => {
    output += `Q${index + 1}. [${q.bloomsLevel.toUpperCase()}] ${q.stem}\n`;
    q.options.forEach((option, i) => {
      const marker = i === q.correctIndex ? '✓' : ' ';
      output += `   ${marker} ${letters[i]}. ${option}\n`;
    });
    output += `   LO: ${q.learningObjectiveRef}\n`;
    output += `   Explanation: ${q.explanation}\n\n`;
  });

  return output;
}

export function downloadReviewSheet(questions, config) {
  const content = generateReviewSheet(questions, config);
  const safeName = config.moduleName
    .replace(/[^a-z0-9]/gi, '_')
    .replace(/_+/g, '_')
    .toLowerCase();
  const filename = `${safeName}_review_sheet.txt`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
